### ISSUE TITLE
ZCML principal directive should define `id` to be unicode on Python 2

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/zope.principalregistry#7]
See zopefoundation/zope.security#4.

In short, the `IPrincipal` interface defines `id` to be a `TextLine`, aka `unicode` on Python 2. But the `IDefinePrincipalDirective` from this package defines `id` to be a, well, `Id`, which is a `NativeStringLine`, aka `BytesLine` on Python 2, meaning that the resulting principal objects aren't valid according to the interface.

The `zope.principalregistry.tests` contains a `principals.zcml` file with these partial contents:
```xml
  <include package="zope.principalregistry" file="meta.zcml"/>

  <principal
      id="zope.p1"
      title="Sir Tim Peters"
      description="Tim Peters"
      login="tim"
      password_manager="SHA1"
      password="40bd001563085fc35165329ea1ff5c5ecbdbbeef"
      />
```

Let's load that file:
```pycon
Python 2.7.13 (default, May  5 2017, 09:16:47)
Type "help", "copyright", "credits" or "license" for more information.
>>> from zope.configuration import xmlconfig
>>> import zope.principalregistry.tests
>>> xmlconfig.file('principal.zcml', zope.principalregistry.tests)
```

Now lets get the resulting principal. We'll note that his resulting `id` is bytes (`str` since this is Python 2):
```pycon
>>> import zope.principalregistry.principalregistry
>>> prin = zope.principalregistry.principalregistry.principalRegistry.getPrincipalByLogin('tim')
>>> prin.id
'zope.p1'
>>> type(prin.id)
<type 'str'>
>>> type(prin.id) is bytes
True
```

Now this object passes the validity tests in zope.interface because it doesn't understand schemas:
```pycon
>>> from zope.security.interfaces import IPrincipal
>>> from zope.interface.verify import verifyObject
>>> verifyObject(IPrincipal, prin)
True
```

But as soon as you bring schema validation in, you see that the id is incorrect:
```pycon
>>> IPrincipal['id']
<zope.schema._bootstrapfields.TextLine object at 0x1076e9210>
>>> IPrincipal['id'].validate(prin.id)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//site-packages/zope/schema/_bootstrapfields.py", line 183, in validate
    self._validate(value)
  File "//site-packages/zope/schema/_bootstrapfields.py", line 310, in _validate
    super(MinMaxLen, self)._validate(value)
  File "//site-packages/zope/schema/_bootstrapfields.py", line 210, in _validate
    raise WrongType(value, self._type, self.__name__)
zope.schema._bootstrapinterfaces.WrongType: ('zope.p1', <type 'unicode'>, 'id')
```

**Comment by jamadden** [comment]
This also extends to the methods of `PrincipalRegistry` like `defineDefaultPrincipal` and `definePrincipal`. Those both produced invalid principals.
